_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 5
                - 53
                - 55
                - 105
            "2":
                - 5
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.6
            "8":
                - 1
                - 5
            "12": 0.19.6
            "13": darwin-arm64
learning_rate:
    value: 0.1
n_estimators:
    value: 100
